name: Build and Test

on:
  push:
    branches: [ tests ]
  pull_request:
    branches: [ tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set up Dafny
      run: | 
        git clone https://github.com/Dargones/dafny.git
        git -C dafny checkout testFrameworkCSharp
        dotnet build dafny/Source/Dafny.sln
        echo $'#!/bin/bash \ndotnet /home/runner/work/dafny-reportgenerator/dafny-reportgenerator/dafny/Binaries/Dafny.dll "$@"' > dafny/Binaries/dafny
        chmod ug+x dafny/Binaries/dafny
        echo 'PATH="$HOME/work/dafny-reportgenerator/dafny-reportgenerator/dafny/Binaries:$PATH"' >> ~/.profile
    - name: Get Z3
      run: |
        wget https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5/z3-4.8.5-x64-ubuntu-16.04.zip
        unzip z3-4.8.5-x64-ubuntu-16.04.zip
        mv z3-4.8.5-x64-ubuntu-16.04 dafny/Binaries/z3
    - name: Verify Dafny code
      run: | 
        source ~/.profile
        dotnet build -t:VerifyDafny -p:VerifyDafnyJobs=2 -p:TestVerifyOverride="verificationLogger:csv"
    - name: Run Tests
      run: |
        source ~/.profile
        dotnet test --verbosity normal
    - name: Self Report
      # Generates a report based on the logged data from verifying itself.
      # This is both a guard against unstable verification and a smoke test of the tool itself.
      run: |
        source ~/.profile
        dotnet run --project src -- summarize-csv-results --max-resource-count 1000000 src/TestResults/*.csv test/TestResults/*.csv
